# This is a basic workflow to help you get started with Actions

name: Terraform Cloud Workspace Create

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: ["api"]
  workflow_dispatch:

env:
  GLOBAL_CONFIG_ENDPOINT: ${{ secrets.GLOBAL_CONFIG_ENDPOINT }}
  VAULT_APPROLE_AUTH_MOUNT: ${{ secrets.VAULT_APPROLE_AUTH_MOUNT }}
  VAULT_APPROLE_ID: ${{ secrets.VAULT_APPROLE_ID }}
  VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  ROOT_CA_CERTIFICATE: ${{ secrets.ROOT_CA_CERTIFICATE }}
  VAULT_CLIENT_CHAIN_CERTIFICATE: ${{ secrets.VAULT_CLIENT_CHAIN_CERTIFICATE }}
  VAULT_CLIENT_PRIVATE_KEY: ${{ secrets.VAULT_CLIENT_PRIVATE_KEY }}

jobs:
  terraform_cloud_workspace_create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r tfe_init/requirements.txt
      - run: python tfe_init/tf_cloud.py ./terraform backend.tf
